# Controls an "Casalux LED Strip" via an ESP32 C3 Super Mini
#
# Strip connected to
# - VIN (5V)
# - D1 / GPIO3
# - GND

esphome:
  name: "led"
  friendly_name: ESP32 C3 Super Mini - LED Strip

  on_boot:
    then:
      - light.turn_on:
          id: led_strip
          effect: "Regenbogen"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  # encryption:
  #   key: "1bpwTpaWXIUiWVzrGZhYKm1W49ark5kfKEdejMD67og="

ota:
  - platform: esphome

wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LED Hotspot"
    password: "led-geheim"

captive_portal:

web_server:

# blink slow: warning; blink fast: error; otherwise off
status_led:
  pin:
    number: GPIO08
    inverted: true
    ignore_strapping_warning: true

# LEDs
light:
  - platform: esp32_rmt_led_strip
    pin: GPIO3
    num_leds: 10
    chipset: ws2812
    name: "RGB LED Strip"
    id: led_strip
    effects:
      - random:
          name: Zufallsfarbe
      - pulse:
          name: Pulsierend
      - addressable_twinkle:
          name: Sternenglitzer einfarbig
      - addressable_random_twinkle:
          name: Sternenglitzer bunt
      - addressable_scan:
          name: Night Rider
      # - strobe:
      # - flicker:
      - addressable_color_wipe:
          name: Buntes Durcheinander
      - addressable_fireworks:
          name: Feuerwerk
      # - addressable_flicker:
      - addressable_rainbow:
          name: Regenbogen